# Generated by Django 4.0.5 on 2022-06-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='True', max_length=100),
            preserve_default=False,
        ),
    ]
