# Generated by Django 4.0.5 on 2022-06-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_alter_comment_post_alter_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='title',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='music',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='app_api.profile'),
        ),
    ]
