from .auth import login_user
from .auth import register_user
from .post import PostView
from .category import CategoryView
from .comment import CommentView
from .profile import ProfileView
from .tag import TagView
from .genre import GenreView
from .user import UserView
from .music import MusicView
